### ISSUE TITLE
Cannot Open PCB Veiw in KiCad Project

### ISSUE THREAD

**Issue by Tauheed-Elahee** [mwelling/lofive#10]
I cannot open the PCB view of the KiCad Project. I am using KiCad 5.1.10, released May 2021. The error says to use KiCad version with a date of 2019-03-11 or newer.

I am running Debian GNU/Linux testing/sid. I am using the flatpak version of the application. The problem also occurs on Windows.

Here is the error I get.
![image](https://user-images.githubusercontent.com/36247967/140833314-a5dfb752-6efa-49da-b14d-93e3aec2dd22.png)

**Comment by mwelling** [comment]
Unfortunately it is not easily possible to revert a design back to an older version of Kicad.

Can you try with the nightly build and see if it opens with that?
https://www.kicad.org/download/debian/
https://downloads.kicad.org/kicad/windows/explore/nightlies

**Comment by Tauheed-Elahee** [comment]
I am using KiCad 5.1.10, it was released May of 2021 (this year). This is the *latest stable* release of *2021*. The error asks for a version that is from *2019 or newer*.

There are no nightly builds for debian.
> There might sometimes some pre versions of upcoming releases available in experimental. These are usually no nightly but a RC (Release Candidate) versions!

- https://downloads.kicad.org/kicad/windows/explore/nightlies

I will try with Windows.

Can you update the project so that it works with KiCad version 5.1.10 (the latest *stable* release)?

**Comment by Tauheed-Elahee** [comment]
I changed to Still in Development (sid) branch on Debian and tried to use the release candidate on the repository it is version 5.1.12 the same error occurs.

**Comment by mwelling** [comment]
When I last updated the design it must have been on a compiled version on my old Debian 10 box.
As you found it does not open with any of the apt install-able versions.

Looks like Ubuntu has a nightly PPA but Debian does not.

I don't want to waste time compiling nightly for Debian so lemme try windows.

**Comment by mwelling** [comment]
Was able to open in 5.99 in Windows, Saving new versions. Ran DRC, fixed a new errors, and repoured the planes.

Get KiCAD 5.99 running and it should open with it now.

![image](https://user-images.githubusercontent.com/1570196/140865354-9812a5f7-8218-483c-86f0-e05bffb5cf61.png)

**Comment by Tauheed-Elahee** [comment]
Thank you.

I was able to install `kicad-nightly` on Debian GNU/Linux. Below are resources and the way I got it installed.

- KiCad forum thread on installing kicad-nightly: [https://forum.kicad.info/t/nightly-builds-for-debian-buster-and-bullseye/27487](https://forum.kicad.info/t/nightly-builds-for-debian-buster-and-bullseye/27487)
- Debian package page for `libglew2.1` a needed dependency for `kicad-nightly`: [https://packages.debian.org/sid/libglew2.1](https://packages.debian.org/sid/libglew2.1)

Steps:
```bash
sudo echo "deb https://debian.sur5r.net/kicad-nightly bullseye main" >> /etc/apt/sources.list   #check to see if it is there. Use text editor if it is not there.

/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/kicad-nightly/pool/main/s/sur5r-keyring/sur5r-keyring_2021.02.02_all.deb sur5r-keyring.deb SHA256:cccfb1dd7d6b1b6a137bb96ea5b5eef18a0a4a6df1d6c0c37832025d2edaa710

sudo dpkg -i ./sur5r-keyring.deb

# install deb package from link above
sudo dpkg -i libglew2.1_2.1.0-4+b1_amd64.deb

sudo apt update

sudo apt install kicad-nightly
```

It works now.

![image](https://user-images.githubusercontent.com/36247967/140991596-ca9a1061-efc7-40dc-829e-c9c2753daabb.png)

I can see why you chose to use the nightly versions. On first glance, the interface is vastly improved and looks like other professional EDA tools.

Is there a plan to move to the stable releases of KiCad once these improvements have been released into a stable release?

**Comment by mwelling** [comment]
https://techexplorations.com/blog/kicad/kicad-6-review-new-and-improved-features/#:~:text=KiCad%206.0%20is%20expected%20to,first%20major%20release%20since%202018.

**Comment by Tauheed-Elahee** [comment]
Looks very promising. I can't wait for it to be released.

Until then, can you add a line in the `README.md` telling the user of the repository to use the nightly version of KiCad for now and detailing how to get it or linking to this issue?

**Comment by mwelling** [comment]
Sure.
