### ISSUE TITLE
Open the SDK

### ISSUE THREAD

**Issue by Layke** [mwelling/lofive#11]
In your Wiki, you mention open the SDK. What do you mean by open?

**Comment by mwelling** [comment]
Sorry for not being clear. I mean open a terminal again and `cd` into the directory of the SDK.

Then you can run the `make` commands to build and program the device.

**Comment by mwelling** [comment]
I updated the wiki to be more clear. Please let me know if you have any other questions.

**Comment by Layke** [comment]
No worries, I'm here to help!

You say open the SDK in a new console, but that still confuses me. What am
I opening?

**Comment by mwelling** [comment]
Opening a terminal window and cd'ing into the sdk directory.

**Comment by Layke** [comment]
Thank you! Compiling the lofive tools right now. Hopefully I get this
little board up and running! Much appreciated!
