### ISSUE TITLE
Missing libraries when opening schematics

### ISSUE THREAD

**Issue by johkra** [mwelling/lofive#2]
When I open the schematics with Kicad 4.0.7, the following libraries are missing:
- e310-g000
- is25lp128
- spx3819
- graphic
- logo
- sn74lvc1g07

Could you add the libraries to the repository, please?

**Comment by mwelling** [comment]
Sure, I will restructure the libraries so they are hosted within the project.

**Comment by mwelling** [comment]
Pull and try it now.

**Comment by johkra** [comment]
Everything opens without errors now. Thank you very much for the quick fix and for publishing the project as open hardware!

(I live in Europe and shipping for the groupgets campaign is almost twice as expensive as the board itself. :-( )

**Comment by mwelling** [comment]
You are welcome.

Yes, I have heard from several countries that the shipping was too much.

You can now order the ICs from Crowd Supply if you are adventurous enough to attempt assembly. The FE310 is a .4mm QFN so I recommend using a solder paste and steel stencil. Another option would be to tin the pads (very carefully) and use a hot air rework station.

**Comment by zigastegu** [comment]
Maybe use US address forwarding service like Shipito.
