### ISSUE TITLE
JTag question

### ISSUE THREAD

**Issue by quantrpeter** [mwelling/lofive#8]
Hi All
   Where i can find information about:
1. using JTag to set the breakpoint in memory and trap the cpu, then single-step running in assembly level?
2. what jtag i can use to work with this board and where i can buy it?
thanks
Peter

**Comment by mwelling** [comment]
The programming method listed here uses JTAG to program the device:
https://github.com/mwelling/lofive/wiki

The segger JLink is also supported:
https://wiki.segger.com/GroupGets_LoFive_R1_1

Either should allow for the use of GDB for debugging.

**Comment by mwelling** [comment]
There is freedom studio that provides a eclipse based graphical IDE if you are interested.

https://www.sifive.com/boards/

I have never tried but let me know if you need help setting it up.
